---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Administration:
    - Portainer:
        icon: portainer.png
        href: "https://portainer.nurul.online"
        description: Container Manager
        # server: my-docker # The docker server that was configured
        # container: portainer

#- Personal:
#    - Nextcloud:
#        icon: nextcloud.png
#        href: "https://nextcloud.nurul.online"
#        description: Storage and Backups

- Monitoring:
    - Grafana:
        icon: grafana.png
        href: "https://grafana.nurul.online"
        description: Metrics Dashboards
    - Prometheus:
        icon: prometheus.png
        href: "https://prometheus.nurul.online"
        description: Metrics Collection
    - Kubernetes Dashboard:
        icon: kubernetes-dashboard.png
        href: "https://k8sdashboard.nurul.online"
        description: Dashboard for Kubernetes
    - Pi-Hole:
        icon: pi-hole.png
        href: "https://pihole.nurul.online/admin"
        description: Block Ads
        widget:
          type: pihole
          url: https://pihole.nurul.online
          key: e17e376d305cc71ab74e867d79ea1503a001d2985468a732941527c28d659226
