---
- hosts: all
  tasks:
      
    - name: Install Docker
      ansible.builtin.shell:
        cmd: |
          curl -sSL https://get.docker.com | sh
          sudo usermod -aG docker pi
        chdir: ~/

    - name: Install Docker Compose
      become: true
      ansible.builtin.apt:
        name: docker-compose
        state: present

    - name: Install Git
      become: true
      ansible.builtin.apt:
        name: git
        state: present

    - name: Flush IP Tables
      ansible.builtin.shell:
        cmd: |
          sudo iptables -F
        chdir: ~/

    - name: Reboot machine
      become: true
      reboot: 

    - name: Install k3s
      become: true
      ansible.builtin.shell:
        cmd: |
          sudo curl -sfL https://get.k3s.io | sh -s - -write-kubeconfig-mode 644 INSTALL_K3S_EXEC="server --disable=traefik"
          sudo chmod 755 /etc/rancher/k3s/k3s.yaml
          mkdir ~/.kube
          sudo cp /etc/rancher/k3s/k3s.yaml ~/.kube/config
        chdir: ~/

    - name: Check k3s Status
      ansible.builtin.command: systemctl status k3s.service
      register: output
    - debug: var=output.stdout_lines

    - name: Install Helm
      ansible.builtin.shell:
        cmd: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
        chdir: ~/