---
- hosts: all
  tasks:

    - name: Deploy Plex
      community.docker.docker_container:
        name: plex
        image: lscr.io/linuxserver/plex:latest
        volumes:
          - /path/to/library:/config
          - /path/to/tvseries:/tv
          - /path/to/movies:/movies
        ports:
          - "32400:32400"
        restart_policy: unless-stopped
        network_mode: host
        # user: 1000:1000
        env:
          VERSION: "docker"
          PUID: "1000"
          PGID: "1000"