---
- hosts: all
  tasks:

    - name: Deploy Pi-Hole
      community.docker.docker_container:
        name: pihole
        image: pihole/pihole:latest
        volumes:
          - './etc-pihole:/etc/pihole'
          - './etc-dnsmasq.d:/etc/dnsmasq.d'
        ports:
          - "54:54/tcp"
          - "54:54/udp"
          - "5335:80/tcp"
        restart_policy: unless-stopped
        env:
          TZ: "Europe/London"
          WEBPASSWORD: 'password123'


