---
- hosts: all
  tasks:

    - name: Create a k8s namespace
      kubernetes.core.k8s:
        name: monitoring
        api_version: v1
        kind: Namespace
        state: present  

    - name: Deploy Prometheus
      kubernetes.core.k8s:
        kubeconfig: ~/.kube/config
        state: present
        definition: "{{ lookup('template', '{{ item }}') | from_yaml }}"
      with_fileglob:
        - "prometheus/clusterRole.yaml"
        - "prometheus/clusterRole-binding.yaml"
        - "prometheus/config-map.yaml"
        - "prometheus/prometheus-deployment.yaml"
        - "prometheus/prometheus-service.yaml"