---
- hosts: all
  tasks:
    - name: Deploy Portainer
      community.docker.docker_container:
        name: portainer
        image: portainer/portainer-ce:latest
        ports:
          - "9000:9000"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - portainer_data:/data
        restart_policy: always

    - name: Deploy Plex
      community.docker.docker_container:
        name: plex
        image: lscr.io/linuxserver/plex:latest
        volumes:
          - /usb256:/media
        restart_policy: unless-stopped
        network_mode: host
        env:
          VERSION: "docker"
          PUID: "1000"
          PGID: "1000"

    - name: Deploy Pi-Hole
      community.docker.docker_container:
        name: pihole
        image: pihole/pihole:latest
        state: started
        dns_servers:
          - 127.0.0.1
          - 8.8.4.4
        volumes:
          - "./etc-pihole:/etc/pihole"
          - "./etc-dnsmasq.d:/etc/dnsmasq.d"
        ports:
          - "54:54/tcp"
          - "54:54/udp"
          - "5335:80/tcp"
        restart_policy: unless-stopped
        env:
          TZ: "Europe/London"
          WEBPASSWORD: "password123"

    - name: Remove old image versions
      docker_prune:
        images: yes
        images_filters:
          dangling: false

    - name: Create Config Folders for Docker Services
      ansible.builtin.shell:
        cmd: |
          mkdir -p /home/pi/heimdall/config
          mkdir -p /home/pi/transmision/config:/config
        chdir: ~/

    - name: Deploy Heimdall
      community.docker.docker_container:
        name: heimdall
        image: lscr.io/linuxserver/heimdall:latest
        state: started
        volumes:
          - "/home/pi/heimdall/config:/config"
        ports:
          - "8090:80"
          - "8100: 443"
        restart_policy: unless-stopped
        env:
          TZ: "Europe/London"
          PUID: "1000"
          PGID: "1000"

    - name: Deploy Transmission
      community.docker.docker_container:
        name: transmission
        image: lscr.io/linuxserver/transmission:latest
        state: started
        volumes:
          - "/home/pi/transmission/config:/config"
        ports:
          - "9091:9091"
          - "51413:51413"
          - "51413:51413/udp"
        restart_policy: unless-stopped
        env:
          TZ: "Europe/London"
          PUID: "1000"
          PGID: "1000"
